### ISSUE TITLE
OTA_2stage: make power pins more accessible

### ISSUE THREAD

**Issue by proppy** [spnadig/GF180_GAFE_1#29]
It would be nice to have vdd and vss on metal4 and outside of the macro to ease power routing.

**Comment by proppy** [comment]
And you can mirror them with something like https://gf180mcu-pdk.readthedocs.io/en/latest/IPs/IO/gf180mcu_fd_io/power.html if you want to be able to probe them.

**Comment by spnadig** [comment]
@njcoburn  - please make the necessary changes

**Comment by spnadig** [comment]
@proppy  - to have it outside of the macro, you mean- run it through open lane without VDD and VSS pads and add VDD and VSS PDK pads manually and send the edited openlane produced GDS to you?

**Comment by proppy** [comment]
nop, sorry I meant make sure there is no metal between the actual pad (p) and the boundary (b) of the macro.

currently the layout looks like this:
```
    M2
|b| M2 (p)
    M2
```
if possible, I think something like this is more desirable:
```
        M2
|b| (p) M2
        M2
```

**Comment by njcoburn** [comment]
Understood. 
![image](https://user-images.githubusercontent.com/63211638/221262159-86500a66-29e0-48cb-825b-e16292f8bc13.png)

**Comment by njcoburn** [comment]
Closing the issue. This was completed - see the image above.
