### ISSUE TITLE
add `Pad` contact to pads

### ISSUE THREAD

**Issue by proppy** [spnadig/GF180_GAFE_1#30]
It seems like the `caravel` does make use of the `Pad` layer, so we should make sure we do too.
![image](https://user-images.githubusercontent.com/5268/221257407-60a31533-2ff9-4b50-b3b1-3c466d1bab8f.png)

**Comment by njcoburn** [comment]
Yes - we have it on all of our pads.

**Comment by njcoburn** [comment]
Any pad we have has the "Pad 37/0" layer. Closing the issue here.
